
    alter table tbl_chat_room_setting 
        drop constraint FK_64bgv7jp59rv5q30oo10ua5wi if exists;

    alter table tbl_chat_room_setting 
        drop constraint FK_l0tc571rf5ans1nvxenhxfs5j if exists;

    alter table tbl_chat_room_setting 
        drop constraint FK_64bgv7jp59rv5q30oo10ua5wi if exists;

    alter table tbl_chat_room_setting 
        drop constraint FK_l0tc571rf5ans1nvxenhxfs5j if exists;

    alter table tbl_location_log 
        drop constraint FK_1bdixhabyd9lqtuynafup1n9h if exists;

    alter table tbl_member 
        drop constraint FK_iy8l6n0l6uvb9mbi412ybxwn5 if exists;

    alter table tbl_message 
        drop constraint FK_rebd9sdkgyjv0q1iii3yldiih if exists;

    alter table tbl_safe_zone 
        drop constraint FK_njp2j62yg1fotihuyv117j8ka if exists;

    drop table tbl_chat_room if exists;

    drop table tbl_chat_room_setting if exists;

    drop table tbl_location_log if exists;

    drop table tbl_member if exists;

    drop table tbl_message if exists;

    drop table tbl_safe_zone if exists;

    drop table tbl_user if exists;

    create table tbl_chat_room (
        id bigint generated by default as identity,
        created_date timestamp not null,
        name varchar(255),
        primary key (id)
    );

    create table tbl_chat_room_setting (
        user_id bigint not null,
        group_id bigint not null,
        alarm_on boolean,
        primary key (user_id, group_id)
    );

    create table tbl_location_log (
        id bigint generated by default as identity,
        created_time timestamp not null,
        latitude DECIMAL(10, 8) not null,
        longitude DECIMAL(11, 8) not null,
        user_id bigint,
        primary key (id)
    );

    create table tbl_member (
        id bigint generated by default as identity,
        age smallint,
        created_date timestamp not null,
        email varchar(255),
        password varchar(255),
        sex integer,
        user_id bigint,
        primary key (id)
    );

    create table tbl_message (
        id bigint generated by default as identity,
        created_time timestamp not null,
        message varchar(255) not null,
        type varchar(255) not null,
        chat_room_id bigint,
        primary key (id)
    );

    create table tbl_safe_zone (
        id bigint generated by default as identity,
        distance integer not null,
        latitude DECIMAL(10, 8) not null,
        longitude DECIMAL(11, 8) not null,
        name varchar(255) not null,
        user_id bigint,
        primary key (id)
    );

    create table tbl_user (
        id bigint generated by default as identity,
        image_path varchar(255),
        nickname varchar(255),
        phone_number varchar(255) not null,
        reg_id varchar(255) not null,
        uuid varchar(255) not null,
        primary key (id)
    );

    alter table tbl_chat_room_setting 
        add constraint FK_64bgv7jp59rv5q30oo10ua5wi 
        foreign key (group_id) 
        references tbl_chat_room;

    alter table tbl_chat_room_setting 
        add constraint FK_l0tc571rf5ans1nvxenhxfs5j 
        foreign key (user_id) 
        references tbl_user;

    alter table tbl_chat_room_setting 
        add constraint FK_64bgv7jp59rv5q30oo10ua5wi 
        foreign key (group_id) 
        references tbl_user;

    alter table tbl_chat_room_setting 
        add constraint FK_l0tc571rf5ans1nvxenhxfs5j 
        foreign key (user_id) 
        references tbl_chat_room;

    alter table tbl_location_log 
        add constraint FK_1bdixhabyd9lqtuynafup1n9h 
        foreign key (user_id) 
        references tbl_user;

    alter table tbl_member 
        add constraint FK_iy8l6n0l6uvb9mbi412ybxwn5 
        foreign key (user_id) 
        references tbl_user;

    alter table tbl_message 
        add constraint FK_rebd9sdkgyjv0q1iii3yldiih 
        foreign key (chat_room_id) 
        references tbl_chat_room;

    alter table tbl_safe_zone 
        add constraint FK_njp2j62yg1fotihuyv117j8ka 
        foreign key (user_id) 
        references tbl_user;
